query Directory($path: String!, $isRecursive: Boolean) {
  directory(path: $path, isRecursive: $isRecursive) {
    canGallery
    canReel
    entries {
      name
      path
      level
      parentName
      isDirectory
      isFile
      isAudio
      isImage
      isVideo
      isShortcut
    }
  }
}
