query Directory($path: String!, $isRecursive: Boolean, $sort: SortOptions) {
  directory(path: $path, isRecursive: $isRecursive, sort: $sort) {
    canGallery
    canReel
    entries {
      name
      date
      path
      level
      parentName
      isDirectory
      isFile
      isAudio
      isImage
      isVideo
      isShortcut
    }
  }
}
