query Directory($path: String!) {
  isDirectoryPinned(path: $path)
  directory(path: $path) {
    canGallery
    entries {
      name
      path
      isDirectory
      isFile
      isImage
      isVideo
    }
  }
}
