query Gallery($path: String!, $page: Int!, $size: Int!) {
  gallery(path: $path, page: $page, size: $size) {
    canGallery
    folderName
    totalImagesCount
    images {
      image
      pageNumber
      url
    }
  }
}
