query Reel($path: String!, $isRecursive: Boolean) {
  reel(path: $path, isRecursive: $isRecursive) {
    canReel
    folderName
    videos {
      extension
      fullName
      folderName
      name
      url
    }
  }
}
